#title: Ahmed Melaih
#logo: docs/assets/Profile_pic2.png
#logo: docs/assets/me_official.png

#description: System Analyst | Data Engineer
#theme: jekyll-theme-Dark-minimal
#theme: minima
#sass:
 # style: compressed

# Uncomment this if not already set
#plugins:
 # - jekyll-feed
 # - jekyll-seo-tag
title: Ahmed Melaih
logo: docs/assets/me_official.png
description: System Analyst | Data Engineer 
#theme: jekyll-theme-dark-minimal
theme: theme: jekyll-theme-dark-minimal

sass:
  style: compressed

url: "https://ahmedmelaih.github.io"
# If this is a project site, set baseurl to "/your-repo-name"
baseurl: ""

collections:
  projects:
    output: true

plugins:
 # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-seo-tag
