title: Ahmed Melaih
#logo: docs/assets/Profile_pic2.png
logo: docs/assets/me_official.png

description: System Analyst | Data Engineer
theme: jekyll-theme-minimal
#theme: minima
sass:
  style: compressed

# Uncomment this if not already set
plugins:
  - jekyll-feed
  - jekyll-seo-tag
