title: "Ahmed Melaih"
description: "Data Science and Engineering"
url: "https://ahmedmelaih.github.io"
author:
  name: "Ahmed Melaih"
  email: "ahmedemlaih@gmail.com"
  url: "ahmedemlaih@gmail.com"
logo: "/assets/me_official.png"
image: "/assets/me_official.png"

#theme: jekyll-theme-minimal
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social usernames (for SEO cards)
social:
  github: AhmedMelaih
  linkedin: ahmedmelaih

sass:
  style: compressed

  include:
  - docs/assets/css/style.css

