#title: Ahmed Melaih
#logo: docs/assets/Profile_pic2.png
#logo: docs/assets/me_official.png

#description: System Analyst | Data Engineer
#theme: jekyll-theme-Dark-minimal
#theme: minima
#sass:
 # style: compressed

# Uncomment this if not already set
#plugins:
 # - jekyll-feed
 # - jekyll-seo-tag
title: "Ahmed Melaih"
description: "System Analyst & Data Engineer | Banking tech, data pipelines, ML for finance (Bahrain)"
url: "https://ahmedmelaih.github.io"
baseurl: ""
author:
  name: "Ahmed Melaih"
  url: "https://ahmedmelaih.github.io"
logo: "/assets/me_official.png"

# Choose ONE of these:
theme: jekyll-theme-minimal   # simple built-in
# remote_theme: alshedivat/al-folio  # richer portfolio theme

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

